### ISSUE TITLE
readable checklist

### ISSUE THREAD

**Issue by yosukeokamo** [yosukeokamo/book#1]
##### 1
- [ ] 明確な単語を選ぶ  ×：get　○：fetch download
- [ ] 汎用的な名前は避ける
  - 誤解されない名前か
- [ ] 具体的な名前を使って物事を詳細に説明する。
- [ ] スコープの大きな変数には長めの名前をつける
- [ ] 大文字やアンダースコアに意味を含める
- [ ] getやsizeは軽量なメソッドであるか
- [ ] 同じような処理をしている場合、シルエットも同じようにしているか
- [ ] 意味の有る順番で、その順番を守ること
##### コメントすべきでないこと
- [ ] コードからすぐに抽出できること
  ##### 記録すべき自分の考え
- [ ] なぜ他のやり方でなく、こうなっているのか
- [ ] コードの欠陥を TODO: と記述しておく
- [ ] 定数の値にまつわる背景
  ##### 読み手の立場に立って考える
- [ ] 読み手が、え？となるような部分にコメントをつけておく
- [ ] ファイルやクラスには全体像のコメントを書く
- [ ] ブロックにコメントをつけて概要をまとめる
- [ ] 複数のものを示す可能性の有る代名詞を避ける
- [ ] 関数の動作はできるだけ正確に説明する
- [ ] コメントに含める入出力の実例を慎重に選ぶ
- [ ] コードの意図は高レベルで記述する。詳細レベルではない。(概要を把握できるように)
- [ ] 引数にはインラインコメントを使ってもよい
- [ ] 邪魔な変数を削除する。結果をすぐに使って、中間変数を削除する
- [ ] 変数のスコープをできるだけ小さくする。
- [ ] final等、一度だけ書き込む変数を利用する
- [ ] 汎用的な処理の場合、固有のコードから汎用コードとして分離する
- [ ] 一度に行うタスクは1つにする。大きなコード、読みにくいコードには複数の機能が実装されていることがある。
- [ ] 最も簡単に問題を解決できる手法であるか
##### テスト
- [ ] テストのトップレベルはできるだけ簡潔にする。
- [ ] テストが失敗したときのために、バグの発見や修正がしやすいようにエラーメッセージを表示する。
- [ ] テスト関数には、何をテストしているのか、どんな状況なのか、を名前にあらわす
